import { RegexReplacePair } from "@shared/Ut";

export const r:RegexReplacePair[] = [
	{regex: /(.)(.)(.)/gm, replacement:'$1二$2三$3'},
	{regex: /(a)二(.*?)三(.*?)/gm, replacement:'kʰʷ二$2三$3'},
	{regex: /(b)二(.*?)三(.*?)/gm, replacement:'b二$2三$3'},
	{regex: /(c)二(.*?)三(.*?)/gm, replacement:'ts二$2三$3'},
	{regex: /(d)二(.*?)三(.*?)/gm, replacement:'$1二$2三$3'},
	{regex: /(e)二(.*?)三(.*?)/gm, replacement:'tʰ二$2三$3'},
	{regex: /(f)二(.*?)三(.*?)/gm, replacement:'pʰ二$2三$3'},
	{regex: /(g)二(.*?)三(.*?)/gm, replacement:'ɡ二$2三$3'},
	{regex: /(h)二(.*?)三(.*?)/gm, replacement:'h二$2三$3'},
	{regex: /(i)二(.*?)三(.*?)/gm, replacement:'kʷ二$2三$3'},
	{regex: /(j)二(.*?)三(.*?)/gm, replacement:'z二$2三$3'},
	{regex: /(k)二(.*?)三(.*?)/gm, replacement:'k二$2三$3'},
	{regex: /(l)二(.*?)三(.*?)/gm, replacement:'$1二$2三$3'},
	{regex: /(m)二(.*?)三(.*?)/gm, replacement:'$1二$2三$3'},
	{regex: /(n)二(.*?)三(.*?)/gm, replacement:'$1二$2三$3'},
	{regex: /(o)二(.*?)三(.*?)/gm, replacement:'lʰ二$2三$3'},
	{regex: /(p)二(.*?)三(.*?)/gm, replacement:'$1二$2三$3'},
	{regex: /(q)二(.*?)三(.*?)/gm, replacement:'ʔ二$2三$3'},
	{regex: /(r)二(.*?)三(.*?)/gm, replacement:'j二$2三$3'},
	{regex: /(s)二(.*?)三(.*?)/gm, replacement:'$1二$2三$3'},
	{regex: /(t)二(.*?)三(.*?)/gm, replacement:'$1二$2三$3'},
	{regex: /(u)二(.*?)三(.*?)/gm, replacement:'ɡʷ二$2三$3'},
	{regex: /(v)二(.*?)三(.*?)/gm, replacement:'tsʰ二$2三$3'},
	{regex: /(w)二(.*?)三(.*?)/gm, replacement:'ŋ二$2三$3'},
	{regex: /(x)二(.*?)三(.*?)/gm, replacement:'kʰ二$2三$3'},
	{regex: /(y)二(.*?)三(.*?)/gm, replacement:'w二$2三$3'},
	{regex: /(z)二(.*?)三(.*?)/gm, replacement:'dz二$2三$3'},
	{regex: /(,)二(.*?)三(.*?)/gm, replacement:'nʰ二$2三$3'},
	{regex: /(\.)二(.*?)三(.*?)/gm, replacement:'mʰ二$2三$3'},
	{regex: /(;)二(.*?)三(.*?)/gm, replacement:'st二$2三$3'},


	{regex: /(.*?)二(a)三(.*?)/gm, replacement:'$1二a三$3'},
	{regex: /(.*?)二(b)三(.*?)/gm, replacement:'$1二ˁu三$3'},
	{regex: /(.*?)二(c)三(.*?)/gm, replacement:'$1二ˁi三$3'},
	{regex: /(.*?)二(d)三(.*?)/gm, replacement:'$1二i三$3'},
	{regex: /(.*?)二(e)三(.*?)/gm, replacement:'$1二ri三$3'},
	{regex: /(.*?)二(f)三(.*?)/gm, replacement:'$1二o三$3'},
	{regex: /(.*?)二(g)三(.*?)/gm, replacement:'$1二g三$3'},
	{regex: /(.*?)二(h)三(.*?)/gm, replacement:'$1二rA三$3'},
	{regex: /(.*?)二(i)三(.*?)/gm, replacement:'$1二rˤi三$3'},
	{regex: /(.*?)二(j)三(.*?)/gm, replacement:'$1二ə三$3'},
	{regex: /(.*?)二(k)三(.*?)/gm, replacement:'$1二rə三$3'},
	{regex: /(.*?)二(l)三(.*?)/gm, replacement:'$1二ˁə三$3'},
	{regex: /(.*?)二(m)三(.*?)/gm, replacement:'$1二rˁə三$3'},
	{regex: /(.*?)二(n)三(.*?)/gm, replacement:'$1二A三$3'},
	{regex: /(.*?)二(o)三(.*?)/gm, replacement:'$1二rˁo三$3'},
	{regex: /(.*?)二(p)三(.*?)/gm, replacement:'$1二rˁe三$3'},
	{regex: /(.*?)二(q)三(.*?)/gm, replacement:'$1二ra三$3'},
	{regex: /(.*?)二(r)三(.*?)/gm, replacement:'$1二ro三$3'},
	{regex: /(.*?)二(s)三(.*?)/gm, replacement:'$1二e三$3'},
	{regex: /(.*?)二(t)三(.*?)/gm, replacement:'$1二ru三$3'},
	{regex: /(.*?)二(u)三(.*?)/gm, replacement:'$1二rˁu三$3'},
	{regex: /(.*?)二(v)三(.*?)/gm, replacement:'$1二ˁo三$3'},
	{regex: /(.*?)二(w)三(.*?)/gm, replacement:'$1二re三$3'},
	{regex: /(.*?)二(x)三(.*?)/gm, replacement:'$1二ˁe三$3'},
	{regex: /(.*?)二(y)三(.*?)/gm, replacement:'$1二rˁa三$3'},
	{regex: /(.*?)二(z)三(.*?)/gm, replacement:'$1二ˁa三$3'},
	//{regex: /(.*?)二(,)三(.*?)/gm, replacement:'$1二$2三$3'},
	//{regex: /(.*?)二(\.)三(.*?)/gm, replacement:'$1二$2三$3'},


	{regex: /(.*?)二(a)三(.*?)/gm, replacement:'$1二$2三$3'},
	{regex: /(.*?)二(b)三(.*?)/gm, replacement:'$1二$2三$3'},
	{regex: /(.*?)二(c)三(.*?)/gm, replacement:'$1二$2三$3'},
	{regex: /(.*?)二(d)三(.*?)/gm, replacement:'$1二$2三$3'},
	{regex: /(.*?)二(e)三(.*?)/gm, replacement:'$1二$2三$3'},
	{regex: /(.*?)二(f)三(.*?)/gm, replacement:'$1二$2三$3'},
	{regex: /(.*?)二(g)三(.*?)/gm, replacement:'$1二$2三$3'},
	{regex: /(.*?)二(h)三(.*?)/gm, replacement:'$1二$2三$3'},
	{regex: /(.*?)二(i)三(.*?)/gm, replacement:'$1二$2三$3'},
	{regex: /(.*?)二(j)三(.*?)/gm, replacement:'$1二$2三$3'},
	{regex: /(.*?)二(k)三(.*?)/gm, replacement:'$1二$2三$3'},
	{regex: /(.*?)二(l)三(.*?)/gm, replacement:'$1二$2三$3'},
	{regex: /(.*?)二(m)三(.*?)/gm, replacement:'$1二$2三$3'},
	{regex: /(.*?)二(n)三(.*?)/gm, replacement:'$1二$2三$3'},
	{regex: /(.*?)二(o)三(.*?)/gm, replacement:'$1二$2三$3'},
	{regex: /(.*?)二(p)三(.*?)/gm, replacement:'$1二$2三$3'},
	{regex: /(.*?)二(q)三(.*?)/gm, replacement:'$1二$2三$3'},
	{regex: /(.*?)二(r)三(.*?)/gm, replacement:'$1二$2三$3'},
	{regex: /(.*?)二(s)三(.*?)/gm, replacement:'$1二$2三$3'},
	{regex: /(.*?)二(t)三(.*?)/gm, replacement:'$1二$2三$3'},
	{regex: /(.*?)二(u)三(.*?)/gm, replacement:'$1二$2三$3'},
	{regex: /(.*?)二(v)三(.*?)/gm, replacement:'$1二$2三$3'},
	{regex: /(.*?)二(w)三(.*?)/gm, replacement:'$1二$2三$3'},
	{regex: /(.*?)二(x)三(.*?)/gm, replacement:'$1二$2三$3'},
	{regex: /(.*?)二(y)三(.*?)/gm, replacement:'$1二$2三$3'},
	{regex: /(.*?)二(z)三(.*?)/gm, replacement:'$1二$2三$3'},
	{regex: /(.*?)二(,)三(.*?)/gm, replacement:'$1二$2三$3'},
	{regex: /(.*?)二(\.)三(.*?)/gm, replacement:'$1二$2三$3'},

	{regex: /(.*?)二(.*?)三(a)/gm, replacement:'$1二$2三'},
	{regex: /(.*?)二(.*?)三(b)/gm, replacement:'$1二$2三ps'},
	{regex: /(.*?)二(.*?)三(c)/gm, replacement:'$1二$2三ns'},
	{regex: /(.*?)二(.*?)三(d)/gm, replacement:'$1二$2三n'},
	{regex: /(.*?)二(.*?)三(e)/gm, replacement:'$1二$2三nʔ'},
	{regex: /(.*?)二(.*?)三(f)/gm, replacement:'$1二$2三m'},
	{regex: /(.*?)二(.*?)三(g)/gm, replacement:'$1二$2三ks'},
	{regex: /(.*?)二(.*?)三(h)/gm, replacement:'$1二$2三j'},
	{regex: /(.*?)二(.*?)三(i)/gm, replacement:'$1二$2三ts'},
	{regex: /(.*?)二(.*?)三(j)/gm, replacement:'$1二$2三w'},
	{regex: /(.*?)二(.*?)三(k)/gm, replacement:'$1二$2三k'},
	{regex: /(.*?)二(.*?)三(l)/gm, replacement:'$1二$2三l'},
	{regex: /(.*?)二(.*?)三(m)/gm, replacement:'$1二$2三ws'},
	{regex: /(.*?)二(.*?)三(n)/gm, replacement:'$1二$2三js'},
	{regex: /(.*?)二(.*?)三(o)/gm, replacement:'$1二$2三lʔ'},
	{regex: /(.*?)二(.*?)三(p)/gm, replacement:'$1二$2三p'},
	{regex: /(.*?)二(.*?)三(q)/gm, replacement:'$1二$2三ʔ'},
	{regex: /(.*?)二(.*?)三(r)/gm, replacement:'$1二$2三mʔ'},
	{regex: /(.*?)二(.*?)三(s)/gm, replacement:'$1二$2三ŋ'},
	{regex: /(.*?)二(.*?)三(t)/gm, replacement:'$1二$2三t'},
	{regex: /(.*?)二(.*?)三(u)/gm, replacement:'$1二$2三wʔ'},
	{regex: /(.*?)二(.*?)三(v)/gm, replacement:'$1二$2三ms'},
	{regex: /(.*?)二(.*?)三(w)/gm, replacement:'$1二$2三ŋʔ'},
	{regex: /(.*?)二(.*?)三(x)/gm, replacement:'$1二$2三ŋs'},
	{regex: /(.*?)二(.*?)三(y)/gm, replacement:'$1二$2三jʔ'},
	{regex: /(.*?)二(.*?)三(z)/gm, replacement:'$1二$2三s'},
	{regex: /(.*?)二(.*?)三(,)/gm, replacement:'$1二$2三wk'},
	{regex: /(.*?)二(.*?)三(\.)/gm, replacement:'$1二$2三ls'},
	{regex: /(.*?)二(.*?)三(.*?)/gm, replacement:'$1$2$3'},



]