import { RegexReplacePair } from "Type"
export const replacePair:RegexReplacePair[] = [
	{regex:/冫/gm, replacement:'im'},
	{regex:/門/gm, replacement:'A'},
	{regex:/目/gm, replacement:'B'},
	{regex:/米/gm, replacement:'F'},
	{regex:/走/gm, replacement:'G'},
	{regex:/禾/gm, replacement:'H'},
	{regex:/魚/gm, replacement:'N'},
	
	{regex:/舟/gm, replacement:'H'},
	{regex:/車/gm, replacement:'J'},
	{regex:/犭/gm, replacement:'K'},
	{regex:/虫/gm, replacement:'L'},
	{regex:/雨/gm, replacement:'M'},
	{regex:/王/gm, replacement:'M'},
	{regex:/石/gm, replacement:'M'},
	{regex:/酉/gm, replacement:'M'},
	{regex:/阝/gm, replacement:'N'},
	{regex:/飠/gm, replacement:'O'},
	{regex:/足/gm, replacement:'R'},
	{regex:/馬/gm, replacement:'S'},
	{regex:/髟/gm, replacement:'S'},
	{regex:/革/gm, replacement:'T'},
	{regex:/糹/gm, replacement:'V'},
	
	{regex:/齒/gm, replacement:'Y'},
	{regex:/辛/gm, replacement:'Y'},
	{regex:/冫/gm, replacement:'I'},
	{regex:/巾/gm, replacement:'L'},
	{regex:/貝/gm, replacement:'B'},
	{regex:/方/gm, replacement:'Y'},
	{regex:/罒/gm, replacement:'W'},
	{regex:/多/gm, replacement:'n'},
	{regex:/氣/gm, replacement:'O'},

	
	{regex:/辶/gm, replacement:'z'},
	{regex:/彳/gm, replacement:'3'},
	{regex:/糹/gm, replacement:'4'},
	{regex:/訁/gm, replacement:'x'},
	{regex:/也/gm, replacement:'5'},
	{regex:/非/gm, replacement:'6'},
	// {regex:/3/gm, replacement:','},
	// {regex:/4/gm, replacement:'.'},
	// {regex:/5/gm, replacement:','},
	// {regex:/6/gm, replacement:'.'},
	{regex:/3/gm, replacement:'<'},
	{regex:/4/gm, replacement:'>'},
	{regex:/5/gm, replacement:'<'},
	{regex:/6/gm, replacement:'>'},

	{regex:/;+$/gm, replacement:''},

	{regex:/^(.)$/gm, replacement:'$1;'},
	//{regex:/^(.)/gm, replacement:'倉$1'},
	{regex:/^(.)(.)(.)(.)(.)$/gm, replacement:'$1$5'},
	{regex:/^(.)(.)(.)(.)$/gm, replacement:'$1$4'},
	{regex:/^(.)(.)(.)$/gm, replacement:'$1$3'},
]